sudo: required
env:
  global:
  - APP_NAME=web-timer
  - PORT=3100
  - DEV_SERVER=SERVER_URL
addons:
  ssh_known_hosts:
  - SERVER_URL
  - SERVER_URL
  - SERVER_URL
before_install:
- ls -la ~/.ssh
- ls -la ~/.ssh/authorized_keys
- touch ~/.ssh/deploy_rsa
- openssl aes-256-cbc -K $encrypted_bf919a6ecdb3_key -iv $encrypted_bf919a6ecdb3_iv
  -in deploy_rsa.enc -out ~\/.ssh/deploy_rsa -d
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/deploy_rsa
- ssh-add -L
- node --version
- pwd
- ls -la
- echo "Running Travis build for $APP_NAME"
after_success:
- mkdir $APP_NAME
- touch $APP_NAME/travis_build_$TRAVIS_JOB_NUMBER
- cp Dockerfile $APP_NAME/Dockerfile
- cp default.conf $APP_NAME/default.conf
- cp .htpasswd $APP_NAME/.htpasswd
- cp index.html $APP_NAME/index.html
- ls -la $APP_NAME
deploy:
- provider: script
  skip_cleanup: true
  script: bash travis_deploy.sh
  on:
    all_branches: true
