sudo: required
env:
  global:
  - APP_NAME=web-timer
  - PORT=3100
addons:
  ssh_known_hosts:
  - ec2-35-176-255-49.eu-west-2.compute.amazonaws.com
  - ec2-35-176-247-34.eu-west-2.compute.amazonaws.com
language: node_js
node_js:
  - "9"
before_install:
- openssl aes-256-cbc -K $encrypted_bf919a6ecdb3_key -iv $encrypted_bf919a6ecdb3_iv
  -in deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
- ls -la ~/.ssh
- chmod 700 ~/.ssh/deploy_rsa
- eval "$(ssh-agent -s)"
- echo -e "Host ${DEV_SERVER}\n" >> ~/.ssh/config
- ssh-add ~/.ssh/deploy_rsa
- ssh-add -L
- pwd
- ls -la
- echo "Running Travis build for ${APP_NAME}"

script:
- echo "hello"
after_success:
- mkdir ${APP_NAME}
- touch ${APP_NAME}/travis_build_$TRAVIS_JOB_NUMBER
- cp Dockerfile ${APP_NAME}/Dockerfile
- cp default.conf ${APP_NAME}/default.conf
- cp .htpasswd ${APP_NAME}/.htpasswd
- cp index.html ${APP_NAME}/index.html
- ls -la ${APP_NAME}
deploy:
- provider: script
  skip_cleanup: true
  script: bash travis_deploy.sh
  on:
    all_branches: true
